// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.DBContext;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619193745_studentMigration")]
    partial class studentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentID"));

                    b.Property<string>("studentAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("StudentAddress");

                    b.Property<int>("studentAge")
                        .HasColumnType("int")
                        .HasColumnName("StudentAge");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("StudentEmail");

                    b.Property<string>("studentMobile")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StudentMobileNumber");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("StudentName");

                    b.HasKey("studentID");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
